### ISSUE TITLE
Improve icon in toolbar

### ISSUE THREAD

**Issue by canboat** [canboat/BR24radar_pi#143]
- Use the new "scaled" vector icon display method from O 4.2.
- Draw an X through the icon if the radar is hidden.
- Change the tooltip according to the hidden/show state.

**Comment by canboat** [comment]
There are now five different icons:

- Grey on grey = Radar hidden
- Grey on grey with large "?" mark = Radar not seen
- Amber on black = Radar on standby in timed transmit mode
- Green on black = Radar on standby
- Green + Red on black = Radar transmitting

**Comment by Hakansv** [comment]
Fix #143 - Increase fatness of radar rings
The initial grey are fine. The rest are still very black, see picture. (And the screen dump is better than live.)
![rw-svg icons](https://cloud.githubusercontent.com/assets/7202854/16815286/80f0d4f4-4939-11e6-8221-b06aa93e0ad8.PNG)

**Comment by canboat** [comment]
Can you measure how large your icons are in pixels?

**Comment by Hakansv** [comment]
Measured with a tool (http://www.arulerforwindows.com/) it's 30 x 30
![rw_icon_mes](https://cloud.githubusercontent.com/assets/7202854/16830149/61997a8e-499d-11e6-9cc8-0e95ba21ccc3.PNG)

**Comment by Hakansv** [comment]
And BTW my screen resolution is one of the most common, 1366 x 768

**Comment by Hakansv** [comment]
New info:
My icons are now slightly better. Strange but I've done two things; PC restart and installed BR24 via the package install.exe instead of just copying the dll. Can't say how either of could made any difference?
But - I still think the black part is somewhat overtaking the picture. What about dark grey??
![rw_icon](https://cloud.githubusercontent.com/assets/7202854/16853951/101f8f6e-4a0f-11e6-9615-92004f0dacbf.PNG)
