### ISSUE TITLE
Range is km although settings is Nm

### ISSUE THREAD

**Issue by Hakansv** [canboat/BR24radar_pi#233]
Today's fetch. Nice job and good cleaned - neither warnings nor errors. Although I've tested trails_performance I'll make live test tomorrow.

The range unit is km while settings is NM
![br24_unit](https://cloud.githubusercontent.com/assets/7202854/18842566/c0564cc0-8415-11e6-9248-c585bdb881d9.PNG)

**Comment by douwefokkema** [comment]
I can't reproduce this issue yet....I will check the code.

**Comment by Hakansv** [comment]
Douwe. You couldn't. - Hmmm - I'm at home using emulator, could that be the cause. I'll check on board tomorrow.

**Comment by canboat** [comment]
This could be related to difference between 4g and br24. The code needs to take the distance in decimeters sent by the radar and map that back to a range, it uses a double lookup but this does depend on it being able to find the exact value right now. This was done so that if you set O to meters but the plotter to NM or viceversa and then let the non O product set a range that the plugin reflects the range selected on that other product. I think this is not the right decision actually.

**Comment by Hakansv** [comment]
This was a simulation, emulator, problem only. Not an issue using a real BR24 radar.
